In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_csv("/home/moeen/projects/GermanCredit-Lens/dataset/raw/german.data")

In [7]:
dataset2=pd.read_csv("/home/moeen/projects/GermanCredit-Lens/dataset/raw/german.data-numeric")

In [8]:
df2=dataset2

In [5]:
df=dataset

In [6]:
df.head()

  A11 6 A34 A43 1169 A65 A75 4 A93 A101 4 A121 67 A143 A152 2 A173 1 A192 A201 1
0  A12 48 A32 A43 5951 A61 A73 2 A92 A101 2 A121 ...
1  A14 12 A34 A46 2096 A61 A74 2 A93 A101 3 A121 ...
2  A11 42 A32 A42 7882 A61 A74 2 A93 A103 4 A122 ...
3  A11 24 A33 A40 4870 A61 A73 3 A93 A101 4 A124 ...
4  A14 36 A32 A46 9055 A65 A73 2 A93 A101 4 A124 ...

In [9]:
df2.head()

  1   6   4  12   5   5   3   4   1  67   3   2   1   2   1   0   0   1   0   0   1   0   0   1   1
0     2  48   2  60   1   3   2   2   1  22   3  ...
1     4  12   4  21   1   4   3   3   1  49   3  ...
2     1  42   2  79   1   4   3   4   2  45   3  ...
3     1  24   3  49   1   3   3   4   4  53   3  ...
4     4  36   2  91   5   3   3   4   4  35   3  ...